package com.homeproject.controlbot.enums;

public enum Marker {
    DELETE_EARNING,
    DELETE_SPENDING,
    SET_EARNING,
    SET_SPENDING,
    EARNING_DATE_IDENTIFICATOR,
    SOME_YEAR_EARNINGS,
    SOME_YEAR_SPENDING,
    SOME_MONTH_EARNING,
    SOME_MONTH_SPENDING,
    SOME_DAY_EARNING,
    SOME_DAY_SPENDING,
    SHOP_NAME,
    DESCRIPTION_PURCHASE,
    SPENDING_DATE_IDENTIFICATOR,
    START_DATE_PROFIT,
    END_DATE_PROFIT,
    YEAR_PROFIT,
    MONTH_PROFIT,
    NONE


}
