package com.homeproject.controlbot.enums;

public enum Marker {
    DELETE_EARNING,
    SET_EARNING,
    SET_SPENDING,
    EARNING_DATE_IDENTIFICATOR,
    SOME_YEAR_EARNINGS,
    SOME_MONTH_EARNING,
    SOME_DAY_EARNING,
    SHOP_NAME,
    DESCRIPTION_PURCHASE,
    SPENDING_DATE_IDENTIFICATOR,
    NONE


}
